### ISSUE TITLE
[Bug] Summary of bug

### ISSUE THREAD

**Issue by papillo12** [murao-kun/Debugify-reforged#1]
### Bug Description

when I try to login to the world the server crashes, I have debugify installed on the server and on the client. I know it's debugify because all this started to happen when I installed it and I don't know if it could be incompatibility with some mod because the server does start well, the problem is when you try to enter the world.

### How to Reproduce?

1. opens the game 
2. log in to the server
3. the server crashes

### Expected Behavior

the server crashes when you try to enter the world

### Version

[Forge 1.19.2] 1.0.0

### Mod Loader Version

1.19.2  43.1.2

### Mod Loader

Forge

### Logs or additional context

server log: [latest (2).log](https://github.com/murao-kun/Debugify-reforged/files/9462899/latest.2.log)

server crash: [crash-2022-08-31_15.41.11-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9462916/crash-2022-08-31_15.41.11-server.txt)

client log: [latest.log](https://github.com/murao-kun/Debugify-reforged/files/9462924/latest.log)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by murao-kun** [comment]
Just tested it in clear instance using only Debugify Reforged on both client and server. Seems like it is working fine as expected. II guess that might be a conflict that you need to find out and report it to me or even not Debugify Reforged at all.

I suggest you to try this:
 - Test if issue still happen without Debugify.

If it is still happening:
 - Make sure you are having same config on both client & server.
 - Find out what mod is conflicting with it.

Sadly this is such boring process, but the only one that can lead to the fix of the issue.

**Comment by papillo12** [comment]
after removing debugify from the server, the server continues to crash, clearly before debugify it was not crashing

**Comment by murao-kun** [comment]
Strange, but if server is crashing without debugify that means that the not issue related to the mod? You can post here crash report and your config and I will have a look again.

**Comment by papillo12** [comment]
Strange, but if server is crashing without debugify that means that the not issue related to the mod? You can post here crash report and your config and I will have a look again.

**Comment by papillo12** [comment]
I can only tell you that the server crashes when I put debugify and when I removed it the server kept crashing, it's like it corrupts the world or I don't know, but as I am testing the server the only solution I had was deleting the world and generating it again but without debugify.

**Comment by papillo12** [comment]
[crash-2022-08-31_16.02.32-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9464714/crash-2022-08-31_16.02.32-server.txt)
[crash-2022-08-31_16.08.42-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9464715/crash-2022-08-31_16.08.42-server.txt)
[crash-2022-08-31_16.05.54-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9464717/crash-2022-08-31_16.05.54-server.txt)

**Comment by papillo12** [comment]
i found the incompatible mod, it's rapidleafdecay https://www.curseforge.com/minecraft/mc-mods/rapid-leaf-decay

**Comment by papillo12** [comment]
never mind, I thought it was that mod but it was not the server crashed, then I thought it was starlight but the server crashed again.

**Comment by papillo12** [comment]
here are more crash reports from yesterday when I was testing if it is a mod causing the problem 

[crash-2022-09-01_04.27.44-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9471835/crash-2022-09-01_04.27.44-server.txt)
[crash-2022-09-01_04.20.41-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9471836/crash-2022-09-01_04.20.41-server.txt)
[crash-2022-09-01_03.56.57-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9471837/crash-2022-09-01_03.56.57-server.txt)
[crash-2022-09-01_04.27.44-server.txt](https://github.com/murao-kun/Debugify-reforged/files/9471838/crash-2022-09-01_04.27.44-server.txt)

**Comment by papillo12** [comment]
I don't have the slightest idea how it was fixed, but in the latest version of forge that came out today the modpack already works.

**Comment by papillo12** [comment]
hi, currently with all the mods that have been updated I can use debugify but I don't know how secure it is, I still updated cloth config and forge to the latest version.

**Comment by papillo12** [comment]
I also saw there that debugify was updated, maybe that will work.
