### ISSUE TITLE
[Bug] Fails to load (Module Resolution Error)

### ISSUE THREAD

**Issue by brisingraerowing** [murao-kun/Debugify-reforged#2]
### Bug Description

Game fails to launch with some other mods (e.g. Suggestion Tweaker)

### How to Reproduce?

1. Launch with this mod and Suggestion Tweaker
2. Module Resolution error in game output

### Expected Behavior

Game loads.

### Version

1.0.0

### Mod Loader Version

1.19.2-43.1.38

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/brisingraerowing/2872bc7f9001517b7330f5889352f744

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by Jusey1** [comment]
I'm having same issue with Forge 43.2.0.
