### ISSUE TITLE
Crash with use of canary

### ISSUE THREAD

**Issue by pat277** [murao-kun/Debugify-reforged#3]
### Bug Description

Use with Canary on Forge 1.19.2 is fatal, despite log calling it a warning

### How to Reproduce?

Launch game

### Expected Behavior

The game to launch

### Version

1.19.2

### Mod Loader Version

43.1.52

### Mod Loader

Forge

### Logs or additional context

[pool-3-thread-1/WARN] [mixin/]: @Redirect conflict. Skipping canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin->@Redirect::getOtherPushableEntities(Lnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/Entity;Lnet/minecraft/world/phys/AABB;Ljava/util/function/Predicate;)Ljava/util/List; with priority 1000, already redirected by debugify-common.mixins.json:basic.client.mc228976.LivingEntityMixin->@Redirect::searchEntities(Lnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/Entity;Lnet/minecraft/world/phys/AABB;Ljava/util/function/Predicate;)Ljava/util/List; with priority 1000

Yes, I know I can disable specific patches, (by doing "MC-228976": false) but if Canary is detected, may as well auto-disable instead of CRASHING HARD.

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by murao-kun** [comment]
Update to latest version, should be fixed.
