### ISSUE TITLE
[Bug] Enabling MC-121706 fails to boot

### ISSUE THREAD

**Issue by MissPotato** [murao-kun/Debugify-reforged#4]
### Bug Description

With this config node enabled the client fails to boot entirely. Considering this is one of three nodes off by default, this is probably a known issue, but reporting it in case it is not.

### How to Reproduce?

1) Set node for MC-121706 to true
2) Launch game
3) Crash

### Version

1.0.0

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/UN33GLAy

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by murao-kun** [comment]
Yeah, this is known issue. Might delete that option at all next update. For now, just do not enable that one.
