### ISSUE TITLE
[Bug] MC-147605 bug when typing "E" in JEI Searchbar it closes the inventory

### ISSUE THREAD

**Issue by DTech10** [murao-kun/Debugify-reforged#8]
### Bug Description

pretty much wat the title says

### How to Reproduce?

1. Open Inventory
2. Click on JEI's Searchbar
3. Type "e"
4. Inventory closes

### Expected Behavior

shouldn't close the inventory
fixed when its disabled

### Version

1.1.0

### Mod Loader Version

1.19.2 - 43.2.23

### Mod Loader

Forge

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by murao-kun** [comment]
Disable MC-147605 in the config.
